### ISSUE TITLE
SHARNESS_TEST_SRCDIR and extensions

### ISSUE THREAD

**Issue by chriscool** [felipec/sharness#103]
Adding `sharness` as a submodule, having a header on each `test.t` as follows:
```
: "${SHARNESS_TEST_DIRECTORY:=.}"
: "${SHARNESS_TEST_SRCDIR:=../sharness}"
. "${SHARNESS_TEST_SRCDIR}/sharness.sh"
```

and `aggregate-results.sh` and `Makefile` can be either copied or symbolic linked, mostly works;

However, it doesn't play well with extensions, because they're loaded from `$SHARNESS_TEST_SRCDIR:` https://github.com/chriscool/sharness/blob/b57a2a49d6b5663388c8a146d7af5fdf63491fc9/sharness.sh#L488

Wouldn't it make more sense to allow those extensions to be tracked alongside the parent project? For that we would need to either load it from `$SHARNESS_TEST_DIRECTORY` or add another env to specify a custom directory. This would allow users to keep the submodule clean without custom changes.

Or am I missing the usecase for sharness.d ?

_Originally posted by @rafasc in https://github.com/chriscool/sharness/pull/102#issuecomment-659572048_

**Comment by chriscool** [comment]
@grondo thanks for the example. I plan to take a look at this soon after #106 and #108 are over.

**Comment by felipec** [comment]
> Wouldn't it make more sense to allow those extensions to be tracked alongside the parent project? For that we would need to either load it from `$SHARNESS_TEST_DIRECTORY` or add another env to specify a custom directory.

Definitely. `$SHARNESS_TEST_DIRECTORY` is fine.
