### ISSUE TITLE
trash dir as home dir when run on Windows

### ISSUE THREAD

**Issue by Vampire** [felipec/sharness#113]
Sharness sets `HOME` to `$SHARNESS_TRASH_DIRECTORY`.
This works fine for *nix systems.
But I just run a test suite on Windows (in this case using bash from Git for Windows) and got real files modified by the tests.
The tested tool is written in Python and when Python looks up the user homedir, it looks for `HOME` only in the *nix variant.

You should also set `USERPROFILE` to `$SHARNESS_TRASH_DIRECTORY`, either always or if Windows is detected.
But even if you do detection, you should always set `HOME`, as the tests might also use that variable directly.

**Comment by felipec** [comment]
You are right, I did a quick test and setting `USERPROFILE` to `$SHARNESS_TRASH_DIRECTORY` does the trick.
