### ISSUE TITLE
testing scripts with sourced functions

### ISSUE THREAD

**Issue by pschmolke** [felipec/sharness#118]
The relative path is not working when testing a script that sources another script.

Let's say we have 
```shell
#!/usr/bin/env bash
# script foo.sh 
# calling another script bar.sh like this
source bar.sh
baz
exit 0
```

and of course 
```shell
#!/usr/bin/env bash
# script bar.sh (in the same directory)
function baz () {
   echo "hello world!"
   exit 0
}
```

Then when I run `sharness` via `prove --verbose`  it fails because it cannot find the `bar.sh` file.
The output is (I did not set a custom `SHARNESS_TRASH_DIRECTORY`): 

`../foo.sh: line 4: bar.sh: No such file or directory` 

Well this is true, but shouldn't it resolve to `../bar.sh` instead?

**Comment by felipec** [comment]
This isn't a problem of the test harness, it's your scripts that can't be run from another directory.

The tests are supposed to create temporary files, so the trash directory has to be somewhere other than the directory of your scripts.

To source other files in an extensible way you need something like:

    source "$(dirname "$(realpath "$0")")"/bar.sh

See this answer in Stack Exchange: [Refer to a file under the same directory of a script found in $PATH](https://unix.stackexchange.com/questions/17717/refer-to-a-file-under-the-same-directory-of-a-script-found-in-path).
