### ISSUE TITLE
Usage with `prove` would need more documentation

### ISSUE THREAD

**Issue by ydirson** [felipec/sharness#122]
I tried to use `prove` as suggested by the README, but with some tests tagged as `EXPENSIVE` I've come on some issues:
- passing `-l` to the test under `prove` is tricky
  - the easiest I found was setting undocumented `TEST_LONG` in the environment
  - a literal `-l` could be likely passed using a wrapper script and `--exec`, but this is so much less comfortable than `TEST_OPTS` offered by the `Makefile` driver
- even then, the skipped expensive tests being counted as success cause a wrong number of "passed tests" (with `prove` only reporting the test files and needing `-v` to show the notes about skipped tests) [Note: to my understanding of [the TAP protocol](http://testanything.org/tap-specification.html) it would be that `prove` itself does not notice the `skip` lines]

That is to say, maybe it would be worth emphasizing the limitations of using `prove` together with `sharness`, and possibly cover alternatives as well to help the user choose.  I did not find a single one listed on the TAP website, and other searches brought nothing more - as if `prove` was the only one of its kind and the norm was to run one's tests by hand and post-process their output with one of the listed viewers.

**Comment by felipec** [comment]
`man prove` says this about arguments to tests:

> It is possible to supply arguments to tests. To do so separate them from prove's own arguments with the arisdottle, '::'. For example
> `prove -v t/mytest.t :: --url http://example.com`
> would run t/mytest.t with the options '--url http://example.com'.  When running multiple tests they will each receive the same arguments.

So you have to do it like `prove :: -l`. This is something about `prove`, not sharness.

The fact that prove counts `SKIP` tests as success is an issue of prove.

> That is to say, maybe it would be worth emphasizing the limitations of using prove together with sharness

This is a limitation of `prove`, not `prove+sharness`.

> and possibly cover alternatives as well to help the user choose.

I started writing my own tool: [rove](https://github.com/felipec/rove), but it doesn't even report the number of successful tests, as I'm not interested in that. I'm mostly interested in knowing if all the tests pass or not.

**Comment by ydirson** [comment]
> So you have to do it like prove :: -l

Damned I had missed that from the `prove` manpage (and it is not the place for discussing its structure ;) ).

> This is something about prove, not sharness

> This is a limitation of prove, not prove+sharness.

Sure, but still it could be useful to let users know that the `Makefile` driver is better than `prove` on this point -- as well as an example of passing options for tests.  If you don't object can propose a PR.

**Comment by ydirson** [comment]
> But a PR to change what? The README is supposed to be short and to the point.

I'd think it could be helpful to add a short note to "Command-line options" about that peculiar `prove test :: flags` syntax.

**Comment by felipec** [comment]
OK. I changed my mind.

I wanted to keep the `README` as simple as possible as the previous maintainer intended. But to be honest I think sharness should interact seamlessly with testing harnesses, and `prove` is the most popular (or even the only truly known one) testing harness.

So I think a short explanation of how to use sharness with `prove` in the `README` could make sense.

Feel free to send a pull request for that.

**Comment by felipec** [comment]
The `README` already mentions `prove`, I've added a page in the wiki with more details about how to use it: [Prove](https://github.com/felipec/sharness/wiki/Prove).

I think that should be enough.
