### ISSUE TITLE
Calling functions from Git submodule fails with v1.2.0 release (Regression)

### ISSUE THREAD

**Issue by LeSpocky** [felipec/sharness#124]
The *README.md* states this:

> Alternatively, you can also add Sharness as a Git submodule to your project.

For my project this is the way I would prefer.  That means *sharness.sh* will not be in the same folder as my tests, but in a subfolder, so I would include `sharness/sharness.sh` instead of `sharness.sh` only.  I obviously don't want to put my tests into the Git Submodule sharness lives in.  This worked fine up to release v1.1.0.

However with v1.2.0 sharness can not source functions, because it expects those to be in `SHARNESS_TEST_SRCDIR/lib-sharness/functions.sh`.  As said above, for the Git Submodule case it's usually not wanted to have your tests and sharness.sh in the same directory.

This could be improved, if that path is not derived from `SHARNESS_TEST_SRCDIR` but from the actual directory *sharness.sh* lives in.
My tests fail like this:

```
% ./mxg.t 
ok 1 - Simple successful test
./mxg.t: 11: test_set_prereq: not found
# passed all 1 test(s)
1..1
```

As you can see it's not possible to call `test_set_prereq` from my test anymore.  At least that function is affected.

**Comment by LeSpocky** [comment]
I think the problem is, I'm not running sharness from bash.  For reference see the commit message of 0bc870552fa4bbd6bb6f8ec135820ae76cdaf1a7 where @felipec explains it already.
There seems to be no easy portable solution to this.  Every shell needs its own approach.  The best I could find where ideas from this lengthy stackoverflow discussion: https://unix.stackexchange.com/q/4650

**Comment by felipec** [comment]
@LeSpocky The commit 0bc8705 explains how this feature works automatically if you are running bash, prior to v1.2.0 the documentation said that you had to manually set `SHARNESS_TEST_SRCDIR`.

Your script needs to set `SHARNESS_TEST_SRCDIR`, then include `$SHARNESS_TEST_SRCDIR/sharness.sh`, which will include `$SHARNESS_TEST_SRCDIR/lib-sharness/functions.sh` automatically.

This was the case before v1.2.0 for all shells, now it's only for shells that are not bash (or zsh). I presume your script isn't doing that.

**Comment by LeSpocky** [comment]
Okay, I build a simple case to reproduce this and put it here: https://github.com/LeSpocky/sharness-issue-124
The initial commit shows what I was trying before, the second one follows your suggestion.  Output before:

```
adahl@ada ../data/adahl/src/tmp/sharness-issue-124 (git)-[master] % sh ./simple.t 
./simple.t: 7: test_set_prereq: not found
ok 1 - Simple successful test
# passed all 1 test(s)
1..1
adahl@ada ../data/adahl/src/tmp/sharness-issue-124 (git)-[master] % zsh ./simple.t
./simple.t:7: command not found: test_set_prereq
ok 1 - Simple successful test
# passed all 1 test(s)
1..1
adahl@ada ../data/adahl/src/tmp/sharness-issue-124 (git)-[master] % bash ./simple.t
ok 1 - Simple successful test
# passed all 1 test(s)
1..1
```

Afterwards everything is fine.  In my opinion the underlying problem is a documentation issue.  See this section from *API.md*:

> `SHARNESS_TEST_SRCDIR`
> ----------------------
> 
> Public: Source directory of test code and sharness library. This directory may be different 
> from the directory in which tests are being run.

This is *not* the directory a user would put test code in.  It's the directory of the sharness source code.  The word "TEST" in variable name and "test code" in explanation is misleading here!

**Comment by felipec** [comment]
> This is not the directory a user would put test code in. It's the directory of the sharness source code. The word "TEST" in variable name and "test code" in explanation is misleading here!

Right. It should probably be called `SHARNESS_SRCDIR.

And the documentation should say "Source directory of the sharness library".

> Also: there's a hint missing, that you MUST set this, if you don't put your tests in the sharness directory.

Well, if you if you don't use bash or zsh. I think most people use bash or zsh, so most people don't need to set this.

So, perhaps the documentation should say it's a good practice to set this variable, but not strictly necessary in most cases.

**Comment by LeSpocky** [comment]
> Well, if you if you don't use bash or zsh. I think most people use bash or zsh, so most people don't need to set this.

I use zsh.  And as you can see in my example output above, setting the variable *is* needed in zsh, otherwise you get the error.  The hack which works for bash doesn't seem to do in zsh.  Here the line with the error shown again, when run in zsh without setting the variable:

```
adahl@ada ../data/adahl/src/tmp/sharness-issue-124 (git)-[master] % zsh ./simple.t
./simple.t:7: command not found: test_set_prereq
ok 1 - Simple successful test
# passed all 1 test(s)
1..1
```

**Comment by felipec** [comment]
> I use zsh.

I see.

I  cloned your example and it indeed failed with zsh (when `SHARNESS_TEST_SRCDIR` is not manually set). The problem seems to be that when zsh support was added (in 00cb93e) that changed the semantics if `$0`.

I've pushed a fix for this, so `SHARNESS_TEST_SRCDIR` should be set correctly by default in zsh too.

I presume this would fix the situation for your use case.

I still think the variable should be renamed to `SHARNESS_SRCDIR` though.

**Comment by felipec** [comment]
OK, I've added a test to make sure the automatic loading of functions works in bash and zsh: a3dc10b.

I've also updated the README to mention in which cases setting `SHARNESS_TEST_SRCDIR` is necessary.

I think with this we can close this issue, but the variable should still be renamed to `SHARNESS_SRCDIR`.

**Comment by LeSpocky** [comment]
Successfully tested the current master.  Thanks for taking care of this. 😃
