### ISSUE TITLE
semi-verbose

### ISSUE THREAD

**Issue by jbenet** [felipec/sharness#14]
:heart: sharness. 

Would be nice to have a semi verbose option, where test cases would be output like in verbose, but only when they fail. Example:

```
ok 1 - current dir is writable
ok 2 - ipfs version succeeds
not ok 3 - ipfs version output looks good

expecting success:
    cat version.txt | egrep "^ipfs version [0-9]+\.[0-9]+\.[0-9]" >/dev/ ||
    cat version.txt && echo && false

ipfs version 0.1.7

ok 4 - ipfs help succeeds
ok 5 - ipfs help output looks good
1..5
```

This is a bit tricky. It might need buffering of the command's stdout/err and redirecting it to dev/null or 1 and 3 when needed (instead of the nice and simple piping of fds). 

But buffering is painful. a poor-man's version might be to enable a different verbose mode where the stdio is still redirected to 1 and 2, but sharness itself remains quiet in passing tests. This way, we can be careful where we send all our io, and make sure only what we want to make it back to sharness does (like `|| cat ...` above). This would enable almost the same thing, at the cost of having to be much more careful with test writing (and weird order).

```
ok 1 - current dir is writable
ok 2 - ipfs version succeeds
# ipfs version 0.1.7
not ok 3 - ipfs version output looks good
#
#   cat version.txt | egrep "^ipfs version [0-9]+\.[0-9]+\.[0-9]" >/dev/ ||
#   cat version.txt | sed -e 's/^/# /' && false
#
ok 4 - ipfs help succeeds
ok 5 - ipfs help output looks good
1..5
```

**Comment by chriscool** [comment]
I just found that Git has a `verbose` command that could help:

https://github.com/git/git/blob/master/t/test-lib-functions.sh#L652

**Comment by chriscool** [comment]
Here are some places where it is used:

https://github.com/git/git/blob/master/t/t0020-crlf.sh#L112
https://github.com/git/git/blob/master/t/t1301-shared-repo.sh#L92
https://github.com/git/git/blob/master/t/t4022-diff-rewrite.sh#L23
https://github.com/git/git/blob/master/t/t4202-log.sh#L116

**Comment by albfan** [comment]
Hi. I want to dig into this. (I can provide PR with some guide)

I use sharness in https://github.com/albfan/bash-ini-parser/

and told contributors to mark test as failure (to describe something known not to work, then fix it and mark test as success.

I use test_cmp to make comparations

Problem is, only failed test are shown with diff error in test-suite.log

https://travis-ci.org/albfan/bash-ini-parser/builds/383820058?utm_source=github_status&utm_medium=notification

I want something like:

make check VERBOSE=failure

so any fail test or expected fail test shows the problem, so I can see in CI what is the problem described

**Comment by albfan** [comment]
By now my trick is to define `verbose=t` and cat test-suite.log after pass test suite

https://github.com/albfan/bash-ini-parser/blob/master/.travis.yml#L7

So I can see the faulting diff https://travis-ci.org/albfan/bash-ini-parser/jobs/384044678#L536

**Comment by chriscool** [comment]
@albfan yeah, a solution to this would be very welcome. I like the idea of a `verbose=failure` mode.

I think the simplest way to implement this might be to have the output of each test sent to a different file and just cat the file if the test failed.

For example in Git [the performance testing part](https://github.com/git/git/tree/master/t/perf) of the test framework outputs the results of a p7821-grep-engines-fixed.sh in test-results/build_17cb5f85d06e82b7837a59064fd5fe61b44f9d12.p7821-grep-engines-fixed.<X>.times where <X> is the test number in the test script.

**Comment by albfan** [comment]
Diving into it I realize all stuff is autotools. So I'm rereading docs https://www.gnu.org/software/automake/manual/html_node/Parallel-Test-Harness.html#Parallel-Test-Harness, and looking where to touch to have this behaviour

Can you explain detail steps to reproduce the git test we can follow to get this done?

**Comment by albfan** [comment]
After this fantastic answer

https://stackoverflow.com/a/21033699/848072

I came out with an implementation

https://github.com/albfan/bash-ini-parser/tree/show-fail-and-expected-fail-details

1. define verbose=t as env var [.travis.yml#L7](https://github.com/albfan/bash-ini-parser/blob/show-fail-and-expected-fail-details/.travis.yml#L7)
2. tweak test-driver to detect failed test and expected failures to cat the log https://github.com/albfan/bash-ini-parser/commit/b67e5172e55017ae6ab1ebc57e02f8f8904d8498
3. define a test expected to success (but failing) [t0006-duplication.sh](https://github.com/albfan/bash-ini-parser/blob/show-fail-and-expected-fail-details/t/t0006-duplication.sh#L9)
4. mark test as expected failure in test suite (`XFAIL_TESTS`) https://github.com/albfan/bash-ini-parser/commit/eaf4802f01cdaab0f7cde382980784e43884e59d

Yay! https://travis-ci.org/albfan/bash-ini-parser/jobs/384330600#L534

For me this trick works, so I would close this as is totally autotools related

About step 1, as test-driver accepts

```
  test-driver --test-name=NAME --log-file=PATH --trs-file=PATH
              [--expect-failure={yes|no}] [--color-tests={yes|no}]
              [--enable-hard-errors={yes|no}] [--]
              TEST-SCRIPT [TEST-SCRIPT-ARGUMENTS]
```

autootols should provide a way to pass those arguments

Did you ever push a patch on autotools?

**Comment by chriscool** [comment]
@albfan no I didn't sent any patch to autotools. Sorry.

I am happy that you found a way to do it that works for you, but I think something could still be done in Sharness so I will keep this open.

**Comment by albfan** [comment]
If I can help just tell me, don't know how to reproduce the test you mention to get things into sharness

**Comment by felipec** [comment]
I don't think this belongs in sharness: this is something the TAP driver should deal with.

What we could do is make the output of `--verbose` be TAP-friendly so the TAP driver can show the comments on failure.

But that's a different feature request.
