### ISSUE TITLE
Import --run option from Git's testsuite

### ISSUE THREAD

**Issue by moy** [felipec/sharness#40]
Since 0445e6f (test-lib: '--run' to run only specific tests, 2014-04-30), Git's test scripts have a `--run` option that would be convenient to have in Sharness.

**Comment by chriscool** [comment]
Yeah I agree. Not sure I will have time to do it soon though.

**Comment by felipec** [comment]
I personally don't have any interest in this feature.

If somebody else does and has enough motivation to port it and sends a pull request I'd take a look at it.
