### ISSUE TITLE
Release tarballs are not signed

### ISSUE THREAD

**Issue by sumpfralle** [felipec/sharness#73]
Currently I fail to find signatures for the [release tarballs](https://github.com/chriscool/sharness/releases).
I would be happy to refer to a gpg signature file for packaging sharness.

**Comment by chriscool** [comment]
Thanks for the suggestion. I am ok to do it for the next release. Not sure it is worth doing for 1.0, but perhaps I can do it for 1.0 at the same time as I do it for the next release.

I think the next release (perhaps 1.1) could come in a few weeks, if possible after shellcheck related PRs and issues have been merged or resolved.

**Comment by sumpfralle** [comment]
For the release: that would be great!

**Comment by chriscool** [comment]
The https://github.com/chriscool/sharness/releases/tag/v1.1.0 release uses a sign tag. I signed it with a new GPG key I created.

I also signed the tarball with the same key and uploaded [the signature file](https://github.com/chriscool/sharness/releases/download/v1.1.0/sharness-1.1.0.tar.gz.asc).

I am not sure my GPG public key is available to verify the signatures though.

**Comment by felipec** [comment]
The instructions in the wiki about how to make a release now have the step to generate the signature: [Release](https://github.com/felipec/sharness/wiki/Release).

The latest release does have a signature attached.
