### ISSUE TITLE
Document usage of "trash" directory

### ISSUE THREAD

**Issue by sumpfralle** [felipec/sharness#86]
I am under the impression, that the usage of the "trash" directory (i.e. all files written to the current directory during the test being removed afterwards) is not well known.

Thus maybe it could deserve being mentioned somewhere. I am reluctant to send a proposal, since I am not sure, where it could be described. I see the following options:
* A) add a sub-heading in README.md
* B) insert a commented example (e.g. with `test_cmp`) into one of the existing examples in README.md
* C) some other file?

What do you think?

**Comment by felipec** [comment]
Initially I created a page in the wiki to explain everything, including the trash directory [About](https://github.com/felipec/sharness/wiki/About), but after thinking more about it I think the trash directory is a fundamental part of Sharness that must be explained right from the get-go.
