### ISSUE TITLE
Document how to release a new Sharness version

### ISSUE THREAD

**Issue by chriscool** [felipec/sharness#89]
This should include the following:

- change SHARNESS_VERSION in sharness.sh
- regenerate the API documentation
- sign the release and publish it on GitHub
- update the CHANGELOG.md

**Comment by felipec** [comment]
I've documented this in my repository: [Release](https://github.com/felipec/sharness/wiki/Release).

I also created a pull request #116 doing these steps so we can move forward and actually release sharness v1.2.0.

**Comment by felipec** [comment]
Unfortunately what I wrote was lost when I deleted my old repo, so I don't know if I'm missing anything from the old version, but I guess we'll find out.
